/* global React */

function PainSection({ lang }) {
  const T = {
    es: { eyebrow: '01 · El punto de partida', title: <>¿Cuántas horas llevas esta semana <em>pensando</em> en cosas que no son tus clientes?</>, cards: [['Facturas y albaranes','Cada semana, el mismo ritual. Papeles, llamadas al gestor, horas que no vuelven.'],['Stock que no cuadra','Materia prima que se pierde. Pedidos que llegan mal. Dinero tirado sin darte cuenta.'],['Reservas por teléfono','Mesas vacías por no-shows. Reservas perdidas. El teléfono sonando cuando tienes las manos ocupadas.'],['Redes abandonadas','Llevan meses sin moverse o las lleva alguien sin tiempo. El negocio invisible para el turista que busca online.']], closer: 'Tú montaste este negocio para otra cosa. Eso se acabó.' },
    en: { eyebrow: '01 · The starting point', title: <>How many hours this week have you spent <em>thinking</em> about things that aren\'t your customers?</>, cards: [['Invoices & receipts','Same ritual every week. Paperwork, calls to the accountant, hours you never get back.'],['Stock that won\'t add up','Wasted ingredients. Orders that arrive wrong. Money slipping through your fingers.'],['Phone-bound reservations','Empty tables from no-shows. Lost bookings. The phone ringing when your hands are full.'],['Forgotten social media','Months without a post, or run by someone with no time. Invisible to tourists searching online.']], closer: 'You started this business for something else. That ends here.' }
  }[lang];
  return (<SlidePanel id="dolor" corner="01 / 07"><div className="panel-eyebrow">{T.eyebrow}</div><h2 className="panel-title">{T.title}</h2><div className="pain-grid">{T.cards.map(([t,b],i)=><div className="pain-card" key={i}><div className="pain-card__num">{String(i+1).padStart(2,'0')} ·</div><h3 className="pain-card__title">{t}</h3><p className="pain-card__body">{b}</p></div>)}</div><p className="pain-closer">— {T.closer} —</p></SlidePanel>);
}

function PromiseSection({ lang }) {
  const T = {
    es: { eyebrow: '02 · La propuesta', title: <>Es como contratar al <em>genio de la lámpara</em>: pides, y se te da.</>, sub: 'Varios expertos trabajando para ti. Pagando menos de lo que cobraría uno solo a media jornada.', list: ['Contabilidad trimestral en menos de 30 minutos','Stock en tiempo real sin contar nada a mano','Reservas online que no dependen del teléfono','Redes con un comando de voz y una foto','Fichaje de empleados resuelto por ley','Equipo sincronizado con los mismos datos','80–90% menos errores y desperdicios','Más reviews captadas de forma natural'], impact: 'Te devolvemos horas preciadas de tu vida.' },
    en: { eyebrow: '02 · The promise', title: <>Like hiring the <em>genie of the lamp</em>: you ask, it\'s done.</>, sub: 'Several experts working for you. Paying less than one part-time hire would cost.', list: ['Quarterly accounting in under 30 minutes','Real-time stock with no manual counting','Online bookings that don\'t depend on the phone','Social posts from a voice note and a photo','Employee time tracking, fully compliant','A team synced on the same data','80–90% fewer errors and waste','More reviews captured naturally'], impact: 'We give you back precious hours of your life.' }
  }[lang];
  return (<SlidePanel id="propuesta" corner="02 / 07"><div className="panel-eyebrow">{T.eyebrow}</div><h2 className="panel-title">{T.title}</h2><p className="panel-subtitle">{T.sub}</p><div className="promise-grid">{T.list.map((item,i)=><div className="promise-item" key={i}><span className="promise-item__mark">{String(i+1).padStart(2,'0')}</span><span className="promise-item__text">{item}</span></div>)}</div><p className="promise-impact">— {T.impact} —</p></SlidePanel>);
}

function ModulesSection({ lang }) {
  const T = {
    es: { eyebrow: '03 · Servicios modulares', title: <>Tú eliges lo que necesitas. <em>Yo me encargo del resto.</em></>, sub: 'No hay paquetes cerrados. Cada negocio es distinto.', tag: 'Tu carta', mods: [['Tu web profesional','En menos de 7 días, una web que parece de restaurante de ciudad, con el sabor de aquí arriba.','597 €','997 €',false],['Google y Tripadvisor','Tu ficha optimizada de arriba a abajo. Reservas de Google activadas.','197 €',null,false],['TPV avanzado con IA','TPV táctil, reservas, comandas, fichaje, takeaway y tienda online.','397 €',null,true,'+ desde 50 €/mes'],['Contabilidad, stock y proveedores','Foto a factura → registrado. Stock en tiempo real. Trimestre listo en 30 minutos.','497 €',null,true],['IA copiloto','Tu asistente invisible que nunca se cansa. Procesos estandarizados, equipo coordinado.','297 €',null,true],['Redes semi-automatizadas','Habla al móvil, sube la foto, publicado. Así de simple.','297 €',null,true],['Fotografía y vídeo','Para que tu web y tus redes transmitan de verdad.','desde 350 €',null,false]], ai: 'Incluye 12 meses de IA' },
    en: { eyebrow: '03 · Modular services', title: <>You choose what you need. <em>I handle the rest.</em></>, sub: 'No fixed packages. Every business is different.', tag: 'Menu', mods: [['Your professional website','In under 7 days, a website that feels like a city restaurant — with the flavor of up here.','€597','€997',false],['Google & Tripadvisor','Your listing optimized top to bottom. Google reservations enabled.','€197',null,false],['Advanced POS with AI','Touch POS, bookings, orders, time tracking, takeaway and online shop.','€397',null,true,'+ from €50/month'],['Accounting, stock & suppliers','Photo to invoice → logged. Real-time stock. Quarter ready in 30 minutes.','€497',null,true],['AI copilot','Your invisible assistant that never tires. Standardized processes, coordinated team.','€297',null,true],['Semi-automated socials','Speak to your phone, upload the photo, published. That simple.','€297',null,true],['Photography & video','So your site and socials really land.','from €350',null,false]], ai: '12 months AI included' }
  }[lang];
  return (<SlidePanel id="modulos" corner="03 / 07"><div className="panel-eyebrow">{T.eyebrow}</div><h2 className="panel-title">{T.title}</h2><p className="panel-subtitle">{T.sub}</p><div className="module-grid">{T.mods.map(([title,body,price,was,ai,sub],i)=><div className="module-card" key={i}><div className="module-card__head"><span className="module-card__num">M · {String(i+1).padStart(2,'0')}</span><span className="module-card__tag">{T.tag}</span></div>{ai&&<div className="module-card__badge">⚡ {T.ai}</div>}<h3 className="module-card__title">{title}</h3><p className="module-card__body">{body}</p><div className="module-card__price">{was&&<s>{was}</s>}<strong>{price}</strong>{sub&&<span style={{color:'var(--text-mute)',fontSize:11}}>{sub}</span>}</div></div>)}</div></SlidePanel>);
}

function AuthorSection({ lang }) {
  const T = {
    es: { eyebrow: '04 · Quién hay detrás', title: <>No soy una agencia random. <em>Soy tu vecino de Bubión.</em></>, body1: 'Me llamo Dan. Granaíno de nacimiento, montañero y nómada. Llevo más de 18 años diseñando sistemas digitales para empresas familiares.', body2: 'Vengo en persona, escucho, observo, audito, te propongo una solución y la monto a tu medida.', stats: [['18+','años en ventas digitales'],['+2 M€','desde 2022 en productos y servicios creados'],['15 días','para web + TPV y copiloto IA funcionando']], pilot: 'El primer restaurante piloto: Los Trotamundos.', cta: 'Ver lostrotamundosalpujarra.com', caption: 'Dan · Bubión, Alpujarra' },
    en: { eyebrow: "04 · Who's behind this", title: <>I'm not an agency. <em>I'm your neighbor in the valley.</em></>, body1: 'My name is Dan. 18+ years designing digital systems for real businesses. Living in Bubión since late 2025.', body2: "I don't come from a city office. I show up in person, listen, observe and build it for you.", stats: [['18+','years in digital sales'],['+€2M','in products & services created'],['7 days','for web + POS live']], pilot: 'The first pilot restaurant: Los Trotamundos.', cta: 'Visit lostrotamundosalpujarra.com', caption: 'Dan · Bubión, Alpujarra' }
  }[lang];
  return (<SlidePanel id="autor" corner="04 / 07"><div className="panel-eyebrow">{T.eyebrow}</div><div className="author-layout"><div><h2 className="panel-title">{T.title}</h2><p className="panel-subtitle" style={{marginBottom:14}}>{T.body1}</p><p className="panel-subtitle">{T.body2}</p><div className="stat-grid">{T.stats.map(([n,l],i)=><div key={i}><div className="stat__num">{n}</div><div className="stat__label">{l}</div></div>)}</div><div className="logo-strip">{['Cliente · 01','Cliente · 02','Cliente · 03','Cliente · 04'].map((c,i)=><div className="logo-cell" key={i}>{c}</div>)}</div><p style={{marginTop:32,color:'var(--text-mute)',fontFamily:'var(--font-display)',fontStyle:'italic',fontSize:18}}>{T.pilot}</p><a className="btn btn--ghost" href="https://lostrotamundosalpujarra.com" target="_blank" rel="noopener" style={{marginTop:20}}>{T.cta} <span className="arrow">→</span></a></div><div className="author-portrait"><div className="author-portrait__caption">{T.caption}</div></div></div></SlidePanel>);
}

function useCountdown(target) {
  const [remain, setRemain] = React.useState(() => Math.max(0, target - Date.now()));
  React.useEffect(() => { const t = setInterval(() => setRemain(Math.max(0, target - Date.now())), 1000); return () => clearInterval(t); }, [target]);
  const s = Math.floor(remain / 1000);
  return { d: Math.floor(s/86400), h: Math.floor((s%86400)/3600), m: Math.floor((s%3600)/60), s: s%60 };
}

function BonusSection({ lang }) {
  const target = React.useMemo(() => new Date('2026-05-10T23:59:00+02:00').getTime(), []);
  const { d, h, m, s } = useCountdown(target);
  const seats = 5, remaining = 5;
  const T = {
    es: { badge: '⚡ Early Adopter', eyebrow: '05 · Bonus fundador', title: <>Solo para los 5 primeros. <em>Solo hasta el 10 de mayo.</em></>, body1: 'Estamos preparando algo que va a cambiar la manera en que los visitantes descubren y consumen en el Barranco del Poqueira.', body2: 'Los 5 primeros negocios que reserven antes del 10 de mayo entran como early adopters.', body3: 'Cuando esto arranque, entenderás por qué importaba ser de los primeros.', labels: ['días','horas','min','seg'], seats: `Quedan ${remaining} de ${seats} plazas`, cta: 'Reservar mi plaza' },
    en: { badge: '⚡ Early Adopter', eyebrow: '05 · Founder bonus', title: <>For the first 5 only. <em>Only until May 10.</em></>, body1: "We're building something that will change how visitors discover and spend in the Poqueira valley.", body2: 'The first 5 businesses to book before May 10 enter as early adopters.', body3: "When this launches, you'll understand why being first mattered.", labels: ['days','hours','min','sec'], seats: `${remaining} of ${seats} seats left`, cta: 'Reserve my seat' }
  }[lang];
  const cells = [[d,T.labels[0]],[h,T.labels[1]],[m,T.labels[2]],[s,T.labels[3]]];
  return (<div className="stack-slot" id="bonus"><div className="slide-panel bonus-panel"><div className="slide-panel__corner">05 / 07</div><div className="bonus-badge">{T.badge}</div><div className="panel-eyebrow">{T.eyebrow}</div><h2 className="panel-title">{T.title}</h2><div className="bonus-grid"><div><p className="panel-subtitle" style={{marginBottom:14}}>{T.body1}</p><p className="panel-subtitle" style={{marginBottom:14}}>{T.body2}</p><p style={{fontFamily:'var(--font-display)',fontStyle:'italic',color:'var(--amber-soft)',fontSize:22,lineHeight:1.4}}>{T.body3}</p></div><div><div className="countdown">{cells.map(([n,l],i)=><div className="cd-cell" key={i}><div className="cd-cell__num">{String(n).padStart(2,'0')}</div><div className="cd-cell__label">{l}</div></div>)}</div><div className="seats"><span>{T.seats}</span><span className="seats__pips">{Array.from({length:seats}).map((_,i)=><span key={i} className={`seats__pip ${i<remaining?'is-on':''}`}/>)}</span></div><a className="btn btn--primary btn--lg" href="#contacto" onClick={(e)=>{e.preventDefault();document.querySelector('#contacto')?.scrollIntoView({behavior:'smooth'});}} style={{marginTop:28}}>{T.cta} <span className="arrow">→</span></a></div></div></div></div>);
}

function PaymentSection({ lang }) {
  const T = {
    es: { eyebrow: '06 · Pago', title: <>Sin <em>excusas</em> para decir que no.</>, cards: [['Pago único','10 % de descuento','Lo más sencillo. Lo más rentable.'],['50 % + 50 %','Sin intereses','La mitad ahora, la mitad al terminar.'],['Financiación','Klarna disponible','Fracciona cómodamente. Decides el ritmo.']] },
    en: { eyebrow: '06 · Payment', title: <>No <em>excuses</em> to say no.</>, cards: [['One-time payment','10% discount','Simplest. Most rewarding.'],['50% + 50%','No interest','Half now, half at delivery.'],['Financing','Klarna available','Split it your way. You set the pace.']] }
  }[lang];
  return (<SlidePanel id="pago" corner="06 / 07"><div className="panel-eyebrow">{T.eyebrow}</div><h2 className="panel-title">{T.title}</h2><div className="pay-grid">{T.cards.map(([t,hl,b],i)=><div className="pay-card" key={i}><div className="pay-card__num">0{i+1} · option</div><h3 className="pay-card__title">{t}</h3><div className="pay-card__hl">{hl}</div><p style={{marginTop:14,color:'var(--text-mute)',fontSize:14,lineHeight:1.6}}>{b}</p></div>)}</div></SlidePanel>);
}

function ContactSection({ lang }) {
  const T = {
    es: { eyebrow: '07 · Conversemos', title: <>El próximo paso es <em>una conversación</em>, sin compromiso.</>, body1: 'Cuéntame cómo funciona tu negocio ahora mismo. Te digo qué módulos tienen más sentido.', body2: 'Sin jerga técnica. Sin presión. Solo dos personas del valle hablando.', labels: ['Tu nombre','Tu negocio','Teléfono o email','Cuéntame qué necesitas'], send: 'Enviar', orWa: 'O escríbeme directamente', where: 'Dónde encontrarme', whereVal: 'Bubión, Alpujarra · Granada', hours: 'Horario de visitas', hoursVal: 'Lun – Sáb · 09:00 – 19:00' },
    en: { eyebrow: "07 · Let's talk", title: <>The next step is <em>a conversation</em>, no commitment.</>, body1: "Tell me how your business runs today. I'll tell you which modules make sense.", body2: 'No technical jargon. No pressure. Just two valley people talking.', labels: ['Your name','Your business','Phone or email','Tell me what you need'], send: 'Send', orWa: 'Or message me directly', where: 'Where to find me', whereVal: 'Bubión, Alpujarra · Granada', hours: 'Visit hours', hoursVal: 'Mon – Sat · 09:00 – 19:00' }
  }[lang];
  const submit = (e) => { e.preventDefault(); alert(lang === 'es' ? '¡Gracias! Te responderé en 24h.' : "Thanks! I'll get back within 24h."); };
  return (<SlidePanel id="contacto" corner="07 / 07"><div className="panel-eyebrow">{T.eyebrow}</div><h2 className="panel-title">{T.title}</h2><p className="panel-subtitle">{T.body1}</p><p className="panel-subtitle" style={{marginTop:-32}}>{T.body2}</p><div className="contact-layout" style={{marginTop:24}}><form className="contact-form" onSubmit={submit}><label>{T.labels[0]} <input type="text" required/></label><label>{T.labels[1]} <input type="text"/></label><label>{T.labels[2]} <input type="text" required/></label><label>{T.labels[3]} <textarea rows={4}/></label><button type="submit" className="btn btn--primary btn--lg" style={{alignSelf:'flex-start',marginTop:8}}>{T.send} <span className="arrow">→</span></button></form><aside className="contact-aside"><div className="contact-aside__row"><span className="contact-aside__label">{T.orWa}</span><a className="contact-aside__val" href="https://wa.me/" target="_blank" rel="noopener">WhatsApp +34 · · ·</a></div><div className="contact-aside__row"><span className="contact-aside__label">Email</span><a className="contact-aside__val" href="mailto:dan@elplandedan.com">dan@elplandedan.com</a></div><div className="contact-aside__row"><span className="contact-aside__label">{T.where}</span><span className="contact-aside__val" style={{fontSize:18}}>{T.whereVal}</span></div><div className="contact-aside__row"><span className="contact-aside__label">{T.hours}</span><span className="contact-aside__val" style={{fontSize:18}}>{T.hoursVal}</span></div></aside></div></SlidePanel>);
}

function Footer({ lang, setLang }) {
  const T = {
    es: { tag: 'Un proyecto de Keen Impact', services: 'Servicios', links: ['Web profesional','Google y Tripadvisor','TPV con IA','Contabilidad','IA copiloto','Reservas online','Automatización de redes','Consultoría de negocio'], legal: 'Legal', legalLinks: ['Aviso legal','Privacidad','Cookies'], copy: '© 2026 Keen Impact · Bubión, Alpujarra · España' },
    en: { tag: 'A Keen Impact project', services: 'Services', links: ['Pro website','Google & Tripadvisor','POS with AI','Accounting','AI copilot','Online bookings','Social automation','Business consulting'], legal: 'Legal', legalLinks: ['Legal notice','Privacy','Cookies'], copy: '© 2026 Keen Impact · Bubión, Alpujarra · Spain' }
  }[lang];
  return (<footer className="footer"><div className="footer__inner"><div className="footer__brand"><h3>FolgaoRest</h3><p style={{fontFamily:'var(--font-mono)',fontSize:11,letterSpacing:'0.18em',color:'var(--text-dim)',textTransform:'uppercase',marginTop:4}}>El restaurante en paz</p><p>{T.tag}</p></div><div className="footer__col"><h4>{T.services}</h4>{T.links.map((l,i)=><a key={i} href="#modulos" onClick={(e)=>{e.preventDefault();document.querySelector('#modulos')?.scrollIntoView({behavior:'smooth'});}}>{l}</a>)}</div><div className="footer__col"><h4>{T.legal}</h4>{T.legalLinks.map((l,i)=><a key={i} href="#">{l}</a>)}</div></div><div className="footer__bottom"><span>{T.copy}</span><span style={{display:'inline-flex',gap:6}}><button onClick={()=>setLang('es')} style={{background:'transparent',border:0,color:lang==='es'?'var(--amber-soft)':'var(--text-dim)',fontFamily:'inherit',fontSize:'inherit',cursor:'pointer'}}>ES</button><span>|</span><button onClick={()=>setLang('en')} style={{background:'transparent',border:0,color:lang==='en'?'var(--amber-soft)':'var(--text-dim)',fontFamily:'inherit',fontSize:'inherit',cursor:'pointer'}}>EN</button></span></div></footer>);
}

Object.assign(window, { PainSection, PromiseSection, ModulesSection, AuthorSection, BonusSection, PaymentSection, ContactSection, Footer });